export const FETCH_USER = "FETCH_USER"

export const GET_PLACES = "GET_PLACES"

// Product types
export const LOADING_PRODUCT = "LOADING_PRODUCT"
export const FETCH_CATEGORIES = "FETCH_CATEGORIES"
export const FETCH_CATEGORIES_ERROR = "FETCH_CATEGORIES_ERROR"
export const FETCH_PROMO_PRODUCTS = "FETCH_PROMO_PRODUCTS"
export const FETCH_PROMO_PRODUCTS_ERROR = "FETCH_PROMO_PRODUCTS_ERROR"
